name: release

on:
  push:
    tags:
      - "**"

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.tag }}
            ghcr.io/${{ github.repository }}:latest

      - name: Deploy by executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            docker ps
            docker image prune -f
            docker pull ghcr.io/${{ github.repository }}:latest
            ls
            cd Project/kfooty && docker-compose up -d
            docker ps
